(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/spin/demo"],{

/***/ "./node_modules/bisheng/tmp/components-spin-demo.index.js":
/*!****************************************************************!*\
  !*** ./node_modules/bisheng/tmp/components-spin-demo.index.js ***!
  \****************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("module.exports = {\n    'basic': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/spin/demo/basic.md */ \"/home/runner/work/4x.ant.design/4x.ant.design/source/node_modules/bisheng/lib/loaders/source-loader!/home/runner/work/4x.ant.design/4x.ant.design/source/components/spin/demo/basic.md\"),\n    'custom-indicator': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/spin/demo/custom-indicator.md */ \"/home/runner/work/4x.ant.design/4x.ant.design/source/node_modules/bisheng/lib/loaders/source-loader!/home/runner/work/4x.ant.design/4x.ant.design/source/components/spin/demo/custom-indicator.md\"),\n    'delayAndDebounce': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/spin/demo/delayAndDebounce.md */ \"/home/runner/work/4x.ant.design/4x.ant.design/source/node_modules/bisheng/lib/loaders/source-loader!/home/runner/work/4x.ant.design/4x.ant.design/source/components/spin/demo/delayAndDebounce.md\"),\n    'inside': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/spin/demo/inside.md */ \"/home/runner/work/4x.ant.design/4x.ant.design/source/node_modules/bisheng/lib/loaders/source-loader!/home/runner/work/4x.ant.design/4x.ant.design/source/components/spin/demo/inside.md\"),\n    'nested': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/spin/demo/nested.md */ \"/home/runner/work/4x.ant.design/4x.ant.design/source/node_modules/bisheng/lib/loaders/source-loader!/home/runner/work/4x.ant.design/4x.ant.design/source/components/spin/demo/nested.md\"),\n    'size': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/spin/demo/size.md */ \"/home/runner/work/4x.ant.design/4x.ant.design/source/node_modules/bisheng/lib/loaders/source-loader!/home/runner/work/4x.ant.design/4x.ant.design/source/components/spin/demo/size.md\"),\n    'tip': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/spin/demo/tip.md */ \"/home/runner/work/4x.ant.design/4x.ant.design/source/node_modules/bisheng/lib/loaders/source-loader!/home/runner/work/4x.ant.design/4x.ant.design/source/components/spin/demo/tip.md\"),\n}\n\n//# sourceURL=webpack:///./node_modules/bisheng/tmp/components-spin-demo.index.js?");

/***/ })

}]);